[versions]

minecraft="1.21.4"
yarn="1.21.4+build.8"

fabric-loader="0.16.10"
fabric-kotlin="1.13.1+kotlin.2.1.10"
fabric-api="0.115.1+1.21.4"

[libraries]

minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
